### ISSUE TITLE
any release file ?

### ISSUE THREAD

**Issue by sgregori** [ninetymiles/dsvideo-launcher#1]
have you got any release file for testing ? 

thanks.

**Comment by ninetymiles** [comment]
Will be there soon :)

SalvaG ***@***.***> 于2022年1月12日周三 23:11写道：

**Comment by ninetymiles** [comment]
https://github.com/ninetymiles/dsvideo-launcher/releases

Here it is


SalvaG ***@***.***> 于2022年1月12日周三 23:11写道：

**Comment by sgregori** [comment]
thank you very much, i will test it inmediately

**Comment by sgregori** [comment]
I tested but seems equal to 1.1.5-10054 original apk from fire tv stick.

There are anyway to set it as default al boot ?

thanks.

**Comment by ninetymiles** [comment]
It just a launcher, just provide an app icon to launch the original DSvideo
apk, because some TV set-top box woks like an AndroidTV, but actually it
was configured as a large tablet, so when install DSvideo TV version apk,
it can not show the DSvideo apk's app icon correctly.

SalvaG ***@***.***> 于2022年1月13日周四 16:07写道：

**Comment by sgregori** [comment]
Ok, thank you for the information and for releasing.
